<a href="https://colab.research.google.com/github/jiw3026/SML/blob/main/xgboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 라이브러리 로딩

In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor

## 데이터 로딩 및 확인

In [2]:
train = pd.read_csv('train.csv') 
test = pd.read_csv('test.csv')

In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      1459 non-null   int64
 1   hour                    1459 non-null   int64
 2   hour_bef_temperature    1457 non-null   float64
 3   hour_bef_precipitation  1457 non-null   float64
 4   hour_bef_windspeed      1450 non-null   float64
 5   hour_bef_humidity       1457 non-null   float64
 6   hour_bef_visibility     1457 non-null   float64
 7   hour_bef_ozone          1383 non-null   float64
 8   hour_bef_pm10           1369 non-null   float64
 9   hour_bef_pm2.5          1342 non-null   float64
 10  count                   1459 non-null   float64
dtypes: float64(9), int64(2)
memory usage: 125.5 KB

In [ ]:
train.describe()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
count,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000,1459.000000
mean,1105.914325,11.493489,16.717433,0.031572,2.479034,52.231297,1405.216884,0.039149,57.168736,30.327124,108.563400
std,631.338681,6.922790,5.235555,0.174797,1.374005,20.356410,582.731618,0.018994,30.774814,14.110562,82.631733
min,3.000000,0.000000,3.100000,0.000000,0.000000,7.000000,78.000000,0.003000,9.000000,8.000000,1.000000
25%,555.500000,5.500000,12.800000,0.000000,1.400000,36.000000,880.000000,0.026000,37.000000,21.000000,37.000000
50%,1115.000000,11.000000,16.600000,0.000000,2.400000,51.000000,1576.000000,0.039149,53.000000,28.000000,96.000000
75%,1651.000000,17.500000,20.050000,0.000000,3.400000,68.500000,1994.000000,0.051000,68.000000,36.000000,150.000000
max,2179.000000,23.000000,30.000000,1.000000,8.000000,99.000000,2000.000000,0.125000,269.000000,90.000000,431.000000

In [ ]:
train.head()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
0,3,20,16.3,1.0,1.5,89.0,576.0,0.027,76.0,33.0,49.0
1,6,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,7,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0
3,8,23,8.1,0.0,2.7,54.0,946.0,0.040,75.0,64.0,57.0
4,9,18,29.5,0.0,4.8,7.0,2000.0,0.057,27.0,11.0,431.0

In [ ]:
test.head()

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5
0,0,7,20.7,0.0,1.3,62.0,954.0,0.041,44.0,27.0
1,1,17,30.0,0.0,5.4,33.0,1590.0,0.061,49.0,36.0
2,2,13,19.0,1.0,2.1,95.0,193.0,0.020,36.0,28.0
3,4,6,22.5,0.0,2.5,60.0,1185.0,0.027,52.0,38.0
4,5,22,14.6,1.0,3.4,93.0,218.0,0.041,18.0,15.0

## 결측치 확인 및 처리

In [ ]:
train.isnull().sum()

id                          0
hour                        0
hour_bef_temperature        2
hour_bef_precipitation      2
hour_bef_windspeed          9
hour_bef_humidity           2
hour_bef_visibility         2
hour_bef_ozone             76
hour_bef_pm10              90
hour_bef_pm2.5            117
count                       0
dtype: int64

In [ ]:
test.isnull().sum()

id                         0
hour                       0
hour_bef_temperature       1
hour_bef_precipitation     1
hour_bef_windspeed         1
hour_bef_humidity          1
hour_bef_visibility        1
hour_bef_ozone            35
hour_bef_pm10             37
hour_bef_pm2.5            36
dtype: int64

In [ ]:
train.fillna(0,inplace = True)
test.fillna(0,inplace = True)

In [3]:
#결측치 처리 - 평균으로
train.fillna(train.mean(),inplace = True)
test.fillna(test.mean(),inplace = True)

In [ ]:
colL  = ['hour','hour_bef_temperature', 'hour_bef_precipitation', 'hour_bef_windspeed', 'hour_bef_humidity', 'hour_bef_visibility', 'hour_bef_visibility',
      'hour_bef_ozone', 'hour_bef_pm10', 'hour_bef_pm2.5', 'count']

train_iqr = train.copy()
for col in colL:
  Q1 = train_iqr[col].quantile(.25)
  Q3 = train_iqr[col].quantile(.75)
  IQR = Q3 - Q1
  train_del = train_iqr[((Q1-1.5*IQR) > train_iqr[col]) | ((Q3+1.5*IQR) < train_iqr[col])]
  train_iqr = train_iqr.drop(train_del.index, axis=0)
train_iqr

,id,hour,hour_bef_temperature,hour_bef_precipitation,hour_bef_windspeed,hour_bef_humidity,hour_bef_visibility,hour_bef_ozone,hour_bef_pm10,hour_bef_pm2.5,count
1,6,13,20.1,0.0,1.4,48.0,916.0,0.042,73.0,40.0,159.0
2,7,6,13.9,0.0,0.7,79.0,1382.0,0.033,32.0,19.0,26.0
5,13,2,13.6,0.0,1.7,80.0,1073.0,0.027,34.0,15.0,39.0
6,14,3,10.6,0.0,1.5,58.0,1548.0,0.038,62.0,33.0,23.0
7,16,21,16.0,0.0,6.0,21.0,1961.0,0.050,90.0,28.0,146.0
...,...,...,...,...,...,...,...,...,...,...,...
1454,2174,4,16.8,0.0,1.6,53.0,2000.0,0.031,37.0,27.0,21.0
1455,2175,3,10.8,0.0,3.8,45.0,2000.0,0.039,34.0,19.0,20.0
1456,2176,5,18.3,0.0,1.9,54.0,2000.0,0.009,30.0,21.0,22.0
1457,2178,21,20.7,0.0,3.7,37.0,1395.0,0.082,71.0,36.0,216.0
1458,2179,17,21.1,0.0,3.1,47.0,1973.0,0.046,38.0,17.0,170.0

## 모델 정의 및 학습

In [ ]:
train_x = train_iqr.drop(['count'],axis = 1)
train_y = train_iqr['count']

In [ ]:
model=RandomForestRegressor(n_estimators=100)
model.fit(train_x,train_y)

RandomForestRegressor()

In [ ]:
import xgboost as xgb
from xgboost import XGBRegressor
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_estimators':[100,200],
    'max_depth': [6,8,10,12],
    'eta':[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
    'colsample_bytree':[0.6, 0.7, 0.8, 0.9],
    'colsample_bylevel':[0.6, 0.7, 0.8, 0.9],
    'max_features': [5,6,8],
    'min_samples_leaf': [1,3,5],
    'min_samples_split': [8,16,20]
}
grid_search = GridSearchCV(XGBRegressor(random_state=42, objective='reg:squarederror',), param_grid, cv=2, n_jobs=1, scoring='neg_mean_squared_error')
grid_search.fit(train_x,train_y)
#그리드서치로 파라미터 찾다가 시간 너무 오래 걸려서 포기했습니다....
#밑에 나온 결과는 이전에 파라미터서치에서 최고성능 나온걸로 돌린 거에요.

KeyboardInterrupt: ignored

In [ ]:
grid_search.best_params_

{'colsample_bylevel': 0.9,
 'colsample_bytree': 0.8,
 'eta': 0.1,
 'max_depth': 6,
 'n_estimators': 100}

In [ ]:
np.sqrt(-grid_search.best_score_)

40.43528673223766

In [ ]:
model = XGBRegressor(objective='reg:squarederror', n_estimators=100, colsample_bylevel=0.9, colsample_bytree=0.8, eta=0.1, max_depth=6)
model.fit(train_x,train_y)

XGBRegressor(colsample_bylevel=0.9, colsample_bytree=0.8, eta=0.1, max_depth=6,
             objective='reg:squarederror')

## 학습 된 모델로 예측 데이터 생성

In [ ]:
pred = model.predict(test)

In [ ]:
acc_train = model.score(train_x, train_y)
acc_train

0.9725230954739486

결측치 0: 0.9716194228431615

결측치 평균: 0.9700297870164062

이상치 처리: 0.9680292116502931

xgboost(파라미터처리 전): 0.8574775514487066

xgboost(파라미터처리 완료): 0.9812504369174797

## 제출파일 생성

In [ ]:
submission = pd.read_csv('submission.csv')
submission

       id  count
0       0    NaN
1       1    NaN
2       2    NaN
3       4    NaN
4       5    NaN
..    ...    ...
710  2148    NaN
711  2149    NaN
712  2165    NaN
713  2166    NaN
714  2177    NaN

[715 rows x 2 columns]

In [ ]:
submission['count'] = pred

In [ ]:
submission

       id       count
0       0  126.799438
1       1  181.176010
2       2   39.143715
3       4   54.431293
4       5   62.225307
..    ...         ...
710  2148   68.753174
711  2149   67.557610
712  2165  114.738358
713  2166  120.255318
714  2177  119.024544

[715 rows x 2 columns]

In [ ]:
submission.to_csv('평균-이상치처리-xgboost(그리드서치2).csv',index = False)

대회 제출시 성능(결측치평균처리, 이상치처리, xgboost파라미터서치 완료): 46.4486967068